language: objective-c
osx_image: xcode7.2

env:
    global:
        - secure: "JPPcWdmNIJiR3YcIwe0LRYce6qDdsiagO+eKKAp7eVk/wD9UHbz96Ms2FFkXxPhRJB1PA6Pf8FpAzIL2YRiJL9jRtKHSvtdF1cSto+57XyBkCsw7PkMVUIxp7fg6Wiwn3H3tucF8jisIkv/Pn7R+9EqePkZSqqu3+ig5AX9ApQ4="
        - KIF_SCREENSHOTS=$PWD/Screens

before_install:
    - brew update 1>/dev/null
    - brew install doxygen nasm yasm optipng imagemagick intltool ninja antlr cmake
    - wget --no-check-certificate https://raw.githubusercontent.com/FFmpeg/gas-preprocessor/master/gas-preprocessor.pl
    - chmod +x gas-preprocessor.pl
    - sudo mv gas-preprocessor.pl /usr/local/bin
    - sudo ln -s /usr/local/bin/glibtoolize /usr/local/bin/libtoolize
    - git submodule update --init --recursive

install:
    - ./prepare.py -d x86_64 -G Ninja
    - make -j4 -s
    - mkdir -p $KIF_SCREENSHOTS

script:
    - xctool -project linphone.xcodeproj -scheme linphone -sdk iphonesimulator -destination name='iPhone 6' build 1>/dev/null
    - xctool -project linphone.xcodeproj -scheme linphone -sdk iphonesimulator -destination name='iPhone 6' test

after_script:
    - ./Tools/imgur_upload.sh
